source 'https://rubygems.org'

gem 'jekyll', '~> 4.4'
gem 'jekyll-paginate', '~> 1.1'
gem 'jekyll-redirect-from', '~> 0.16'
gem 'jekyll-seo-tag', '~> 2.8'
gem 'jekyll-sitemap', '~> 1.4'
gem 'jemoji', '~> 0.13'
gem 'chronic', '~> 0.10'
gem 'rake', '~> 13.3'
gem 'yt', '~> 0.34'
gem 'pry', '~> 0.15'
gem 'webrick', '~> 1.9'
