source 'https://rubygems.org'

gem 'jekyll', '3.8.5'
gem 'github-pages', '204'
gem 'jekyll-paginate'
gem 'jekyll-redirect-from'
gem 'jekyll-seo-tag'
gem 'jekyll-sitemap'
gem 'jemoji'
gem 'chronic'
gem 'rake'
gem 'yt'
gem 'pry'
